### ISSUE TITLE
SeqDiva vs Mac Big Sur OS

### ISSUE THREAD

**Issue by 000generic** [eancedeg/SeqDivA#1]
Hi,

I have been using SeqDivA this week and its worked fantastic (and been really useful) on my MacBook Pro and the Catalina OS. I updated to my Mac OS to Big Sur yesterday and tried SeqDiva today but the python script freezes and the graphic interface does not pop up.

I installed all SeqDivA dependencies in a conda environment that includes Python 3.7.10.  Everything seems good - just the python script freezes up now.  

Any ideas or suggestions...?

Thank you :)

**Comment by eancedeg** [comment]
In principle SeqDiVa should work fine with python>=3.7. In my particular case I have a virtual environment with python==3.8.6 and it works perfectly. Apart from the dependencies listed in the requirements.txt file remember that SeqDivA needs to have the emboss tool installed to provide SeqDivA with the needle and water commands in the PATH. Please check that the water and needle commands are in the PATH and report any errors. In my case I run SeqDivA on Ubuntu 20.04.

**Comment by 000generic** [comment]
I reinstalled everything - using only conda-forge versions of the pre-requisites and things are working again.  Thank you :)
